from __future__ import annotations

import ast
from pathlib import Path


AGENT_CORE = Path(__file__).resolve().parents[1] / "agent_core"
ROOT = Path(__file__).resolve().parents[1]


def test_agent_core_has_no_runtime_or_provider_imports() -> None:
    forbidden_prefixes = (
        "app.openai_agents_runtime",
        "app.tools",
        "app.graph",
        "app.knowledge",
        "app.api",
        "app.core.redis_client",
        "openai",
        "agents",
        "fastapi",
        "mcp",
        "redis",
        "sqlalchemy",
    )
    offenders: list[tuple[str, str]] = []

    for path in AGENT_CORE.glob("*.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            for name in names:
                if any(name == prefix or name.startswith(prefix + ".") for prefix in forbidden_prefixes):
                    offenders.append((path.name, name))

    assert offenders == []


def test_agent_core_package_root_exports_stable_base_api() -> None:
    import agent_core

    expected = {
        "AgentRunner",
        "AgentSession",
        "AgentHarness",
        "AgentManagerCapacityError",
        "AgentManagerConcurrencyPolicy",
        "AgentPromptBudgetPlan",
        "AgentPromptBuilder",
        "AgentResumeRequest",
        "ApprovalCenter",
        "ApprovalDecisionRecord",
        "ApprovalGrant",
        "ApprovalQueueFilter",
        "ApprovalQueueView",
        "ApprovalRecord",
        "ApprovalResolution",
        "ApprovalResumeContext",
        "ApprovalStorePort",
        "AgentRunQuery",
        "AgentRunStorePort",
        "AgentRunTraceBundle",
        "AgentRunPreflightCenter",
        "AgentRunPreflightCheckPort",
        "AgentRunPreflightCheckRecord",
        "AgentRunPreflightIssue",
        "AgentRunPreflightReport",
        "AgentRunPreflightRequest",
        "AgentRunPreflightRequirements",
        "AgentToolRuntime",
        "AgentToolSpec",
        "AgentToolTrace",
        "CapabilityDiscoveryResult",
        "CapabilityKind",
        "CapabilityMatch",
        "CapabilityQuery",
        "ContextInjection",
        "ContextInjectionDecision",
        "ContextInjectionDecisionStatus",
        "ContextInjectionPolicy",
        "ContextInjectionTrace",
        "ContextMaterialSelectionTrace",
        "ContextMaterial",
        "ContextMaterialCallRecord",
        "ContextMaterialCenter",
        "ContextMaterialQuery",
        "ContextMaterialQueryMode",
        "ContextMaterialRoute",
        "ContextMaterialSearchPlan",
        "ContextMaterialSelection",
        "ContextMaterialSelectionRequest",
        "ContextMaterialSelectionResult",
        "ContextMaterialSelectionStatus",
        "ContextMaterialSelectorPort",
        "ContextMaterialStoreNotFoundError",
        "ContextMaterialStorePort",
        "ContextMaterialStoreSpec",
        "ContextReducerPort",
        "DefaultLLMProviderCodec",
        "DefaultContextReducer",
        "DefaultContextMaterialSelector",
        "DefaultPromptSemanticReducer",
        "DefaultTraceEvaluator",
        "DeterministicEmbeddingProvider",
        "EmbeddingProviderCenter",
        "EmbeddingProviderPort",
        "EmbeddingRequest",
        "EmbeddingResponse",
        "ExternalMemoryCallRecord",
        "ExternalContextMaterialStore",
        "ExternalMemoryStore",
        "HandoffDecision",
        "HandoffRecord",
        "HandoffRequest",
        "HandoffRouter",
        "HandoffRouterPort",
        "HandoffSpec",
        "HandoffTrace",
        "ReActExecutor",
        "InMemoryPlanner",
        "InMemoryPlannerStore",
        "JsonStructuredOutputValidator",
        "InMemoryApprovalStore",
        "InMemoryAgentRunStore",
        "InMemoryArtifactStore",
        "InMemoryContextMaterialStore",
        "InMemoryRunTraceStore",
        "MarkdownApprovalStore",
        "MarkdownAgentRunStore",
        "MarkdownArtifactStore",
        "MarkdownPlannerStore",
        "MarkdownRunTraceStore",
        "InMemoryToolReplayStore",
        "EventLogPort",
        "EventStreamBatch",
        "EventStreamCursor",
        "ListEventSink",
        "MarkdownEventSink",
        "NullApprovalStore",
        "NullRunTraceStore",
        "NullToolReplay",
        "NullEventSink",
        "LLMProviderCenter",
        "LLMCallRecord",
        "LLMModelCapabilities",
        "LLMProviderCodecPort",
        "LLMProviderRouteCandidate",
        "LLMProviderRoutePlan",
        "LLMRequestShapePlan",
        "LLMContentPart",
        "LLMMessage",
        "LLMResponseFormat",
        "LLMToolChoice",
        "LLMToolContract",
        "AgentLifecycleEvent",
        "AgentLifecycleHookCenter",
        "AgentLifecycleHookPort",
        "AgentLifecycleHookRecord",
        "LifecycleEventType",
        "LifecycleHookStatus",
        "NullLifecycleHooks",
        "ToolCenter",
        "ToolCenterCallRecord",
        "ToolCenterTrace",
        "ToolRegistry",
        "ToolRouteCandidate",
        "ToolRoutePlan",
        "SkillRegistry",
        "MCPCenter",
        "MCPInventoryRefreshResult",
        "MCPStdioJSONRPCConnector",
        "MemoryBackendKind",
        "MemoryCenter",
        "MemoryGovernanceTrace",
        "MemoryQueryMode",
        "MemoryRoute",
        "MemorySearchPlan",
        "MultiAgentCoordinator",
        "AgentJournalStorePort",
        "InMemoryJournalStore",
        "MarkdownJournalStore",
        "PersistentAgentJournal",
        "PersistentPlanner",
        "AgentJournalReplay",
        "AgentReplayEvent",
        "ReplayIssue",
        "SQLiteAgentJournal",
        "SQLiteEventSink",
        "SQLiteApprovalStore",
        "SQLiteAgentRunStore",
        "SQLiteArtifactStore",
        "SQLiteJournalStore",
        "SQLiteRunTraceStore",
        "SQLiteToolReplayStore",
        "SQLiteMemoryStore",
        "SQLiteContextMaterialStore",
        "SQLitePlannerStore",
        "MarkdownMemoryStore",
        "MarkdownContextMaterialStore",
        "MarkdownToolReplayStore",
        "StorageBackendKind",
        "StorageBackendPreflightReport",
        "StorageBackendCandidate",
        "StorageBackendCatalog",
        "StorageBackendRequirement",
        "StorageBackendRole",
        "StorageBackendSelection",
        "StorageBackendSpec",
        "StorageBackendTrace",
        "storage_backend_catalog_from_components",
        "storage_backend_manifests_from_components",
        "RuleBasedPolicy",
        "RuleBasedMemoryGovernance",
        "PersistentToolReplay",
        "PlanExecutionReport",
        "PlanExecutionStatus",
        "PlanExecutionStep",
        "PlanExecutor",
        "PlannerStorePort",
        "DEFAULT_PROMPT_TRIM_ORDER",
        "DEFAULT_PROMPT_TRIM_RULES",
        "LLMRetryPolicy",
        "LLMStreamEvent",
        "LLMUsageLimits",
        "LLMTransportPort",
        "LLMToolCall",
        "PromptBucketBudgetDecision",
        "PromptBucketBudgetPolicy",
        "PromptBucketBudgetResult",
        "PromptBucketBudgetRule",
        "PromptSemanticReducerPort",
        "PromptSemanticTrimDecision",
        "PromptSemanticTrimRequest",
        "PromptSemanticTrimResult",
        "PromptTrimPlan",
        "PromptTrimResult",
        "PromptTrimRule",
        "PromptTrimStep",
        "ReducerRequest",
        "ReducerResult",
        "ResumeCandidate",
        "ResumeIndex",
        "RetryHint",
        "RunTraceStorePort",
        "RunTraceQuery",
        "RunInterrupt",
        "RunInterruptKind",
        "SchemaValidationIssue",
        "SchemaValidationResult",
        "StructuredOutputResult",
        "StructuredOutputSpec",
        "StructuredOutputValidatorPort",
        "StaticRunPreflightCheck",
        "default_agent_run_preflight_center",
        "UsageInfo",
        "ToolReplayRecord",
        "ToolReplayStorePort",
        "TraceCorrelationEntry",
        "TraceCorrelationIndex",
        "TraceEvalHarness",
        "TraceEvalIssue",
        "TraceEvalReport",
        "TraceEvalSpec",
        "TraceEvaluatorPort",
        "TraceReplayComparator",
        "TraceReplayDiffIssue",
        "TraceReplayDiffReport",
        "TraceReplayDiffSpec",
        "TraceReplayHarness",
        "TraceReplayResult",
        "TraceReplayStep",
        "TransportLLMProvider",
        "agent_tool_spec_from_session",
        "apply_reduction_to_timeline",
        "handoff_spec_from_session",
        "storage_backend_manifest",
        "validate_json_schema_subset",
        "validate_tool_arguments",
    }

    assert expected <= set(agent_core.__all__)
    for name in expected:
        assert getattr(agent_core, name) is not None


def test_repository_does_not_ship_runtime_adapter_packages() -> None:
    forbidden_dirs = {
        "adapters",
        "integrations",
        "openai_agents_runtime",
        "graphiti",
        "raven_runtime",
    }
    offenders = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.iterdir()
        if path.is_dir() and path.name in forbidden_dirs
    ]

    assert offenders == []

