"""Provider-neutral AI agent core primitives.

The package is deliberately independent from RavenStorm's runtime adapters,
OpenAI Agents SDK, FastAPI, Redis, databases, and concrete tool implementations.
"""

from typing import Any

from agent_core.acceptance import (
    AgentCoreAcceptanceHarness,
    AgentCoreAcceptanceIssue,
    AgentCoreAcceptanceReport,
    run_agent_core_acceptance as _run_agent_core_acceptance,
)
from agent_core.approval_acceptance import (
    AgentCoreApprovalAcceptanceHarness,
    AgentCoreApprovalAcceptanceIssue,
    AgentCoreApprovalAcceptanceReport,
    run_agent_core_approval_acceptance,
)
from agent_core.actions import (
    ActionRegistry,
    ActionSpec,
    ActionVerification,
    ActionVerifierPort,
    ParsedAction,
)
from agent_core.approvals import (
    ApprovalCenter,
    ApprovalDecisionRecord,
    ApprovalDecisionStatus,
    ApprovalGrant,
    ApprovalQueueFilter,
    ApprovalQueueView,
    ApprovalRecord,
    ApprovalResolution,
    ApprovalResumeContext,
    ApprovalStatus,
    ApprovalStorePort,
    InMemoryApprovalStore,
    MarkdownApprovalStore,
    NullApprovalStore,
    SQLiteApprovalStore,
)
from agent_core.artifacts import (
    ArtifactRecord,
    ArtifactStorePort,
    InMemoryArtifactStore,
    MarkdownArtifactStore,
    SQLiteArtifactStore,
)
from agent_core.backends import (
    StorageBackendCandidate,
    StorageBackendCatalog,
    StorageBackendKind,
    StorageBackendPreflightReport,
    StorageBackendRequirement,
    StorageBackendRole,
    StorageBackendSelection,
    StorageBackendSpec,
    storage_backend_catalog_from_components,
    storage_backend_manifests_from_components,
    storage_backend_manifest,
)
from agent_core.capabilities import (
    CapabilityCatalog,
    CapabilityDiscoveryResult,
    CapabilityKind,
    CapabilityMatch,
    CapabilityQuery,
)
from agent_core.config import AgentProfile, CapabilitySet, RuntimeBudget
from agent_core.context import (
    AgentContextPack,
    AgentPromptBuilder,
    ContextInjection,
    ContextInjectionDecision,
    ContextInjectionDecisionStatus,
    ContextInjectionPolicy,
    ContextMaterial,
    ContextMaterialCallRecord,
    ContextMaterialCenter,
    ContextMaterialQuery,
    ContextMaterialQueryMode,
    ContextMaterialRoute,
    ContextMaterialSearchPlan,
    ContextMaterialSelection,
    ContextMaterialSelectionRequest,
    ContextMaterialSelectionResult,
    ContextMaterialSelectionStatus,
    ContextMaterialSelectorPort,
    ContextMaterialStoreNotFoundError,
    ContextMaterialStorePort,
    ContextMaterialStoreSpec,
    DefaultContextMaterialSelector,
    ExternalContextMaterialStore,
    InMemoryContextMaterialStore,
    MarkdownContextMaterialStore,
    SQLiteContextMaterialStore,
)
from agent_core.context_acceptance import (
    AgentCoreContextAcceptanceHarness,
    AgentCoreContextAcceptanceIssue,
    AgentCoreContextAcceptanceReport,
    run_agent_core_context_acceptance,
)
from agent_core.orchestration_acceptance import (
    AgentCoreOrchestrationAcceptanceHarness,
    AgentCoreOrchestrationAcceptanceIssue,
    AgentCoreOrchestrationAcceptanceReport,
    run_agent_core_orchestration_acceptance,
)
from agent_core.provider_acceptance import (
    AgentCoreProviderAcceptanceHarness,
    AgentCoreProviderAcceptanceIssue,
    AgentCoreProviderAcceptanceReport,
    run_agent_core_provider_acceptance,
)
from agent_core.embeddings import (
    DeterministicEmbeddingProvider,
    EmbeddingCallRecord,
    EmbeddingInput,
    EmbeddingProviderCenter,
    EmbeddingProviderNotFoundError,
    EmbeddingProviderPort,
    EmbeddingProviderSpec,
    EmbeddingRequest,
    EmbeddingResponse,
    EmbeddingRoute,
    EmbeddingVector,
    SemanticSearchHit,
    cosine_similarity,
    deterministic_text_embedding,
    rank_semantic_documents,
)
from agent_core.errors import ErrorClassification, FailureKind, classify_error
from agent_core.events import (
    AgentEvent,
    EventLogPort,
    EventSinkPort,
    EventStreamBatch,
    EventStreamCursor,
    EventStreamTail,
    ListEventSink,
    MarkdownEventSink,
    NullEventSink,
    SQLiteEventSink,
)
from agent_core.evals import (
    DefaultTraceEvaluator,
    TraceEvalHarness,
    TraceEvalIssue,
    TraceEvalReport,
    TraceEvalSpec,
    TraceEvaluatorPort,
    TraceReplayComparator,
    TraceReplayDiffIssue,
    TraceReplayDiffReport,
    TraceReplayDiffSpec,
    TraceReplayHarness,
    TraceReplayResult,
    TraceReplayStep,
)
from agent_core.harness import (
    AgentHarness,
    AgentJournalSnapshot,
    AgentJournalStorePort,
    CancelToken,
    Checkpoint,
    InMemoryAgentJournal,
    InMemoryJournalStore,
    MarkdownJournalStore,
    PersistentAgentJournal,
    ResumeCandidate,
    ResumeIndex,
    ResumePlan,
    ResumePlanIssue,
    ResumePlanIssueSeverity,
    ResumeToken,
    RunInterrupt,
    RunInterruptKind,
    RunStatus,
    RunState,
    SQLiteAgentJournal,
    SQLiteJournalStore,
    TERMINAL_RUN_STATUSES,
    TERMINAL_TURN_STATUSES,
    TurnStatus,
    TurnState,
)
from agent_core.lifecycle import (
    AgentLifecycleEvent,
    AgentLifecycleHookCenter,
    AgentLifecycleHookPort,
    AgentLifecycleHookRecord,
    LifecycleEventType,
    LifecycleHookStatus,
    NullLifecycleHooks,
)
from agent_core.manifest import (
    AgentCoreAPIContract,
    AgentCoreAPIStabilityReport,
    AgentCoreCapability,
    AgentCoreReadinessIssue,
    AgentCoreReadinessProfile,
    AgentCoreReadinessReport,
    AgentCoreRuntimeBoundary,
    AgentCoreSDKManifest,
    agent_core_api_contract as _build_agent_core_api_contract,
    agent_core_sdk_manifest as _build_agent_core_sdk_manifest,
    agent_core_replacement_readiness_profile,
    default_agent_core_capabilities,
    evaluate_agent_core_api_stability as _evaluate_agent_core_api_stability,
    evaluate_agent_core_readiness as _evaluate_agent_core_readiness,
)
from agent_core.loop_guard import LoopGuard, LoopGuardConfig, LoopGuardDecision
from agent_core.memory import (
    AllowAllMemoryGovernance,
    ExternalMemoryCallRecord,
    ExternalMemoryStore,
    InMemoryMemoryStore,
    MarkdownMemoryStore,
    MemoryBackendKind,
    MemoryCenter,
    MemoryGovernanceDecision,
    MemoryGovernanceDeniedError,
    MemoryGovernancePort,
    MemoryHit,
    MemoryPort,
    MemoryQuery,
    MemoryQueryMode,
    MemoryRecord,
    MemoryRoute,
    MemorySearchPlan,
    MemoryStoreNotFoundError,
    MemoryStoreSpec,
    MemoryWrite,
    RuleBasedMemoryGovernance,
    SQLiteMemoryStore,
)
from agent_core.mcp import (
    MCPCenter,
    MCPContextMaterialRecord,
    MCPContextMaterialRequest,
    MCPContextMaterialResult,
    MCPConnectorPort,
    MCPInventoryRefreshResult,
    MCPPromptContent,
    MCPPromptSpec,
    MCPRefreshResult,
    MCPResourceContent,
    MCPResourceSpec,
    MCPServerSpec,
    MCPServerState,
    MCPToolReference,
    MCPToolSpec,
)
from agent_core.mcp_stdio import MCPStdioConnectorConfig, MCPStdioJSONRPCConnector
from agent_core.policy import (
    AllowAllPolicy,
    ApprovalRequest,
    CompositePolicy,
    InMemoryPolicyDecisionStore,
    MarkdownPolicyDecisionStore,
    NullPolicyDecisionStore,
    PolicyDecision,
    PolicyDecisionRecord,
    PolicyDecisionStorePort,
    PolicyRule,
    PolicySubjectKind,
    RuleBasedPolicy,
    SQLitePolicyDecisionStore,
)
from agent_core.preflight import (
    AgentRunPreflightCenter,
    AgentRunPreflightCheckPort,
    AgentRunPreflightCheckRecord,
    AgentRunPreflightIssue,
    AgentRunPreflightReport,
    AgentRunPreflightRequest,
    AgentRunPreflightRequirements,
    StaticRunPreflightCheck,
    default_agent_run_preflight_center,
)
from agent_core.planner import (
    InMemoryPlanner,
    InMemoryPlannerStore,
    MarkdownPlannerStore,
    Plan,
    PlanExecutionReport,
    PlanExecutionStatus,
    PlanExecutionStep,
    PlanExecutor,
    PersistentPlanner,
    PlannerPort,
    PlannerStorePort,
    PlanStep,
    PlanStepStatus,
    PlanUpdate,
    SQLitePlannerStore,
    TERMINAL_PLAN_STEP_STATUSES,
)
from agent_core.prompt import (
    DEFAULT_PROMPT_TRIM_ORDER,
    DEFAULT_PROMPT_TRIM_RULES,
    DefaultPromptSemanticReducer,
    PromptBucket,
    PromptBucketBudgetDecision,
    PromptBucketBudgetPolicy,
    PromptBucketBudgetResult,
    PromptBucketBudgetRule,
    PromptBucketRole,
    PromptIR,
    PromptSemanticReducerPort,
    PromptSemanticTrimDecision,
    PromptSemanticTrimRequest,
    PromptSemanticTrimResult,
    PromptTrimPlan,
    PromptTrimResult,
    PromptTrimRule,
    PromptTrimStep,
)
from agent_core.providers import (
    DefaultLLMProviderCodec,
    LLMContentPart,
    LLMCallRecord,
    LLMModelCapabilities,
    LLMProviderCenter,
    LLMProviderCodecPort,
    LLMBudgetExceededError,
    LLMMessage,
    LLMProviderError,
    LLMProviderNotFoundError,
    LLMProviderPort,
    LLMRequestShapePlan,
    LLMProviderRouteCandidate,
    LLMProviderRoute,
    LLMProviderRoutePlan,
    LLMProviderSpec,
    LLMRequest,
    LLMResponse,
    LLMResponseFormat,
    LLMRetryPolicy,
    LLMStreamEvent,
    LLMStreamAccumulator,
    LLMToolCall,
    LLMToolChoice,
    LLMToolContract,
    LLMUsageLimits,
    LLMTransportPort,
    OpenAICompatibleLLMProviderCodec,
    RetryHint,
    TransportLLMProvider,
    UsageInfo,
)
from agent_core.react import ReActConfig, ReActExecutor, ReActResult
from agent_core.reducer import (
    ContextReducerPort,
    DefaultContextReducer,
    ReducerRequest,
    ReducerResult,
    apply_reduction_to_timeline,
)
from agent_core.recovery import (
    AgentCoreRecoveryHarness,
    AgentCoreRecoveryIssue,
    AgentCoreRecoveryReport,
    run_agent_core_recovery_acceptance,
)
from agent_core.resume_acceptance import (
    AgentCoreResumeAcceptanceHarness,
    AgentCoreResumeAcceptanceIssue,
    AgentCoreResumeAcceptanceReport,
    run_agent_core_resume_acceptance,
)
from agent_core.storage_acceptance import (
    AgentCoreStorageAcceptanceHarness,
    AgentCoreStorageAcceptanceIssue,
    AgentCoreStorageAcceptanceReport,
    run_agent_core_storage_acceptance,
)
from agent_core.runner import (
    AgentManagerCapacityError,
    AgentManagerCapacityStatus,
    AgentManagerConcurrencyPolicy,
    AgentManagerScheduleSnapshot,
    AgentPromptBudgetPlan,
    AgentResumeRequest,
    AgentRunner,
    AgentRunOutcome,
    AgentRunQuery,
    AgentRunRequest,
    AgentRunStorePort,
    AgentSession,
    AgentSessionManager,
    InMemoryAgentRunStore,
    MarkdownAgentRunStore,
    ManagedAgentRun,
    SQLiteAgentRunStore,
)
from agent_core.schema import (
    SchemaValidationIssue,
    SchemaValidationResult,
    validate_json_schema_subset,
)
from agent_core.handoff import (
    AgentToolRuntime,
    AgentToolSpec,
    HandoffDecision,
    HandoffDecisionStatus,
    HandoffRecord,
    HandoffRequest,
    HandoffRouter,
    HandoffRouterPort,
    HandoffSpec,
    MultiAgentCoordinator,
    agent_tool_spec_from_session,
    handoff_spec_from_session,
)
from agent_core.skills import (
    SkillRegistry,
    SkillSpec,
    SkillsContext,
    SkillViewWindow,
    compute_skill_hash,
    parse_skill_resource_ref,
    skill_from_markdown,
)
from agent_core.structured import (
    JsonStructuredOutputValidator,
    StructuredOutputResult,
    StructuredOutputSpec,
    StructuredOutputValidatorPort,
    structured_output_feedback,
)
from agent_core.trace import (
    AgentJournalReplay,
    AgentReplayEvent,
    AgentRunTraceBundle,
    AgentToolTrace,
    ApprovalTrace,
    ArtifactTrace,
    CapabilityTrace,
    ContextInjectionTrace,
    ContextMaterialSelectionTrace,
    CostTrace,
    HandoffTrace,
    InMemoryRunTraceStore,
    MarkdownRunTraceStore,
    MCPCenterTrace,
    MemoryGovernanceTrace,
    NullRunTraceStore,
    PlannerTrace,
    PromptTrace,
    ReplayIssue,
    RunTraceQuery,
    RunTraceStorePort,
    SQLiteRunTraceStore,
    SkillCenterTrace,
    StorageBackendTrace,
    StructuredOutputTrace,
    ToolCenterTrace,
    ToolTrace,
    TraceCorrelationEntry,
    TraceCorrelationIndex,
)
from agent_core.validation import (
    AgentCoreRuntimeBoundaryHit,
    AgentCoreRuntimeBoundaryReport,
    AgentCoreValidationIssue,
    AgentCoreValidationReport,
    AgentCoreValidationSuite,
    evaluate_agent_core_runtime_boundary as _evaluate_agent_core_runtime_boundary,
    run_agent_core_validation as _run_agent_core_validation,
)
from agent_core.tools import (
    InMemoryToolReplay,
    InMemoryToolReplayStore,
    MarkdownToolReplayStore,
    NullToolReplay,
    PersistentToolReplay,
    SQLiteToolReplayStore,
    ToolCenter,
    ToolCenterCallRecord,
    ToolExecutionAttempt,
    ToolExecutionCenter,
    ToolExecutionRecord,
    ToolInvocation,
    ToolRouteCandidate,
    ToolRoutePlan,
    ToolReplayRecord,
    ToolReplayPort,
    ToolReplayStorePort,
    ToolResult,
    ToolRegistry,
    ToolRuntimeMount,
    ToolRuntimePort,
    ToolRetryPolicy,
    ToolSpec,
    validate_tool_arguments,
)

__all__ = [
    "ActionRegistry",
    "ActionSpec",
    "ActionVerification",
    "ActionVerifierPort",
    "ApprovalDecisionRecord",
    "ApprovalDecisionStatus",
    "ApprovalCenter",
    "ApprovalGrant",
    "ApprovalQueueFilter",
    "ApprovalQueueView",
    "ApprovalRecord",
    "ApprovalResolution",
    "ApprovalResumeContext",
    "ApprovalStorePort",
    "AllowAllPolicy",
    "AllowAllMemoryGovernance",
    "AgentContextPack",
    "AgentCoreAcceptanceHarness",
    "AgentCoreAcceptanceIssue",
    "AgentCoreAcceptanceReport",
    "AgentCoreAPIContract",
    "AgentCoreAPIStabilityReport",
    "AgentCoreApprovalAcceptanceHarness",
    "AgentCoreApprovalAcceptanceIssue",
    "AgentCoreApprovalAcceptanceReport",
    "AgentCoreCapability",
    "AgentCoreContextAcceptanceHarness",
    "AgentCoreContextAcceptanceIssue",
    "AgentCoreContextAcceptanceReport",
    "AgentCoreOrchestrationAcceptanceHarness",
    "AgentCoreOrchestrationAcceptanceIssue",
    "AgentCoreOrchestrationAcceptanceReport",
    "AgentCoreProviderAcceptanceHarness",
    "AgentCoreProviderAcceptanceIssue",
    "AgentCoreProviderAcceptanceReport",
    "AgentCoreReadinessIssue",
    "AgentCoreReadinessProfile",
    "AgentCoreReadinessReport",
    "AgentCoreRecoveryHarness",
    "AgentCoreRecoveryIssue",
    "AgentCoreRecoveryReport",
    "AgentCoreResumeAcceptanceHarness",
    "AgentCoreResumeAcceptanceIssue",
    "AgentCoreResumeAcceptanceReport",
    "AgentCoreRuntimeBoundaryHit",
    "AgentCoreRuntimeBoundaryReport",
    "AgentCoreRuntimeBoundary",
    "AgentCoreSDKManifest",
    "AgentCoreStorageAcceptanceHarness",
    "AgentCoreStorageAcceptanceIssue",
    "AgentCoreStorageAcceptanceReport",
    "AgentCoreValidationIssue",
    "AgentCoreValidationReport",
    "AgentCoreValidationSuite",
    "AgentEvent",
    "AgentHarness",
    "AgentJournalSnapshot",
    "AgentJournalStorePort",
    "AgentJournalReplay",
    "AgentManagerCapacityError",
    "AgentManagerCapacityStatus",
    "AgentManagerConcurrencyPolicy",
    "AgentManagerScheduleSnapshot",
    "AgentPromptBudgetPlan",
    "AgentPromptBuilder",
    "AgentResumeRequest",
    "AgentProfile",
    "AgentRunner",
    "AgentRunOutcome",
    "AgentRunQuery",
    "AgentRunRequest",
    "AgentRunStorePort",
    "AgentReplayEvent",
    "AgentRunTraceBundle",
    "AgentRunPreflightCenter",
    "AgentRunPreflightCheckPort",
    "AgentRunPreflightCheckRecord",
    "AgentRunPreflightIssue",
    "AgentRunPreflightReport",
    "AgentRunPreflightRequest",
    "AgentRunPreflightRequirements",
    "AgentToolTrace",
    "ApprovalTrace",
    "ArtifactTrace",
    "AgentSession",
    "AgentSessionManager",
    "AgentToolRuntime",
    "AgentToolSpec",
    "ArtifactRecord",
    "ArtifactStorePort",
    "ApprovalRequest",
    "ApprovalStatus",
    "CapabilitySet",
    "CapabilityCatalog",
    "CapabilityDiscoveryResult",
    "CapabilityKind",
    "CapabilityMatch",
    "CapabilityQuery",
    "CancelToken",
    "CapabilityTrace",
    "CompositePolicy",
    "Checkpoint",
    "ContextInjection",
    "ContextInjectionDecision",
    "ContextInjectionDecisionStatus",
    "ContextInjectionPolicy",
    "ContextInjectionTrace",
    "ContextMaterialSelectionTrace",
    "ContextMaterial",
    "ContextMaterialCallRecord",
    "ContextMaterialCenter",
    "ContextMaterialQuery",
    "ContextMaterialQueryMode",
    "ContextMaterialRoute",
    "ContextMaterialSearchPlan",
    "ContextMaterialSelection",
    "ContextMaterialSelectionRequest",
    "ContextMaterialSelectionResult",
    "ContextMaterialSelectionStatus",
    "ContextMaterialSelectorPort",
    "ContextMaterialStoreNotFoundError",
    "ContextMaterialStorePort",
    "ContextMaterialStoreSpec",
    "ContextReducerPort",
    "CostTrace",
    "InMemoryRunTraceStore",
    "MarkdownRunTraceStore",
    "MCPCenterTrace",
    "NullRunTraceStore",
    "PlannerTrace",
    "DefaultContextReducer",
    "DefaultContextMaterialSelector",
    "ExternalContextMaterialStore",
    "InMemoryContextMaterialStore",
    "MarkdownContextMaterialStore",
    "SQLiteContextMaterialStore",
    "DefaultPromptSemanticReducer",
    "DeterministicEmbeddingProvider",
    "EmbeddingCallRecord",
    "EmbeddingInput",
    "EmbeddingProviderCenter",
    "EmbeddingProviderNotFoundError",
    "EmbeddingProviderPort",
    "EmbeddingProviderSpec",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "EmbeddingRoute",
    "EmbeddingVector",
    "DefaultLLMProviderCodec",
    "LLMContentPart",
    "DefaultTraceEvaluator",
    "EventSinkPort",
    "EventLogPort",
    "ErrorClassification",
    "EventStreamBatch",
    "EventStreamCursor",
    "EventStreamTail",
    "FailureKind",
    "ExternalMemoryCallRecord",
    "ExternalMemoryStore",
    "HandoffDecision",
    "HandoffDecisionStatus",
    "HandoffRecord",
    "HandoffRequest",
    "HandoffRouter",
    "HandoffRouterPort",
    "HandoffSpec",
    "HandoffTrace",
    "ListEventSink",
    "MarkdownEventSink",
    "NullEventSink",
    "DEFAULT_PROMPT_TRIM_ORDER",
    "DEFAULT_PROMPT_TRIM_RULES",
    "LLMProviderPort",
    "LLMProviderCodecPort",
    "LLMCallRecord",
    "LLMProviderCenter",
    "LLMBudgetExceededError",
    "LLMMessage",
    "LLMProviderError",
    "LLMProviderNotFoundError",
    "LLMProviderRoute",
    "LLMProviderRouteCandidate",
    "LLMProviderRoutePlan",
    "LLMRequestShapePlan",
    "LLMProviderSpec",
    "LLMModelCapabilities",
    "LLMRequest",
    "LLMResponse",
    "LLMResponseFormat",
    "LLMRetryPolicy",
    "LLMStreamEvent",
    "LLMStreamAccumulator",
    "LLMToolCall",
    "LLMToolChoice",
    "LLMToolContract",
    "LLMUsageLimits",
    "LLMTransportPort",
    "OpenAICompatibleLLMProviderCodec",
    "AgentLifecycleEvent",
    "AgentLifecycleHookCenter",
    "AgentLifecycleHookPort",
    "AgentLifecycleHookRecord",
    "LifecycleEventType",
    "LifecycleHookStatus",
    "NullLifecycleHooks",
    "LoopGuard",
    "LoopGuardConfig",
    "LoopGuardDecision",
    "MCPCenter",
    "MCPContextMaterialRecord",
    "MCPContextMaterialRequest",
    "MCPContextMaterialResult",
    "MCPConnectorPort",
    "MCPInventoryRefreshResult",
    "MCPPromptContent",
    "MCPPromptSpec",
    "MCPRefreshResult",
    "MCPResourceContent",
    "MCPResourceSpec",
    "MCPServerSpec",
    "MCPServerState",
    "MCPStdioConnectorConfig",
    "MCPStdioJSONRPCConnector",
    "MCPToolReference",
    "MCPToolSpec",
    "Plan",
    "PlanExecutionReport",
    "PlanExecutionStatus",
    "PlanExecutionStep",
    "PlanExecutor",
    "PlannerPort",
    "PlannerStorePort",
    "PlanStep",
    "PlanStepStatus",
    "PlanUpdate",
    "ParsedAction",
    "PolicyDecision",
    "PolicyDecisionRecord",
    "PolicyDecisionStorePort",
    "PolicyRule",
    "PolicySubjectKind",
    "PromptBucket",
    "PromptBucketBudgetDecision",
    "PromptBucketBudgetPolicy",
    "PromptBucketBudgetResult",
    "PromptBucketBudgetRule",
    "PromptBucketRole",
    "PromptIR",
    "PromptSemanticReducerPort",
    "PromptSemanticTrimDecision",
    "PromptSemanticTrimRequest",
    "PromptSemanticTrimResult",
    "PromptTrimPlan",
    "PromptTrimResult",
    "PromptTrimRule",
    "PromptTrimStep",
    "PromptTrace",
    "ReActConfig",
    "ReActExecutor",
    "ReActResult",
    "ReducerRequest",
    "ReducerResult",
    "ResumeCandidate",
    "ResumeIndex",
    "ResumePlan",
    "ResumePlanIssue",
    "ResumePlanIssueSeverity",
    "ResumeToken",
    "ReplayIssue",
    "RunTraceStorePort",
    "RunTraceQuery",
    "RetryHint",
    "RunInterrupt",
    "RunInterruptKind",
    "RunStatus",
    "RunState",
    "RuleBasedPolicy",
    "RuntimeBudget",
    "SQLiteAgentJournal",
    "SQLiteEventSink",
    "classify_error",
    "SQLiteJournalStore",
    "SkillRegistry",
    "SkillSpec",
    "SkillsContext",
    "SkillCenterTrace",
    "SkillViewWindow",
    "StorageBackendCandidate",
    "StorageBackendCatalog",
    "StorageBackendKind",
    "StorageBackendPreflightReport",
    "StorageBackendRequirement",
    "StorageBackendRole",
    "StorageBackendSelection",
    "StorageBackendSpec",
    "storage_backend_catalog_from_components",
    "storage_backend_manifests_from_components",
    "StorageBackendTrace",
    "StructuredOutputTrace",
    "agent_tool_spec_from_session",
    "compute_skill_hash",
    "apply_reduction_to_timeline",
    "handoff_spec_from_session",
    "parse_skill_resource_ref",
    "skill_from_markdown",
    "InMemoryToolReplay",
    "InMemoryToolReplayStore",
    "MarkdownToolReplayStore",
    "InMemoryAgentJournal",
    "InMemoryArtifactStore",
    "MarkdownArtifactStore",
    "InMemoryApprovalStore",
    "InMemoryAgentRunStore",
    "InMemoryJournalStore",
    "InMemoryMemoryStore",
    "InMemoryPlanner",
    "InMemoryPlannerStore",
    "JsonStructuredOutputValidator",
    "MarkdownPlannerStore",
    "MarkdownMemoryStore",
    "MarkdownJournalStore",
    "MarkdownApprovalStore",
    "MarkdownAgentRunStore",
    "MemoryCenter",
    "MemoryGovernanceDecision",
    "MemoryGovernanceDeniedError",
    "MemoryGovernancePort",
    "MemoryGovernanceTrace",
    "MemoryHit",
    "MemoryBackendKind",
    "MemoryPort",
    "MemoryQuery",
    "MemoryQueryMode",
    "MemoryRecord",
    "MemoryRoute",
    "MemorySearchPlan",
    "MemoryStoreNotFoundError",
    "MemoryStoreSpec",
    "MemoryWrite",
    "ManagedAgentRun",
    "MultiAgentCoordinator",
    "NullApprovalStore",
    "NullPolicyDecisionStore",
    "NullToolReplay",
    "PersistentAgentJournal",
    "PersistentPlanner",
    "PersistentToolReplay",
    "RuleBasedMemoryGovernance",
    "InMemoryPolicyDecisionStore",
    "MarkdownPolicyDecisionStore",
    "SQLiteApprovalStore",
    "SQLiteAgentRunStore",
    "SQLiteArtifactStore",
    "SQLiteToolReplayStore",
    "SQLiteRunTraceStore",
    "SQLiteMemoryStore",
    "SQLitePlannerStore",
    "SQLitePolicyDecisionStore",
    "StaticRunPreflightCheck",
    "SchemaValidationIssue",
    "SchemaValidationResult",
    "SemanticSearchHit",
    "StructuredOutputResult",
    "StructuredOutputSpec",
    "StructuredOutputValidatorPort",
    "default_agent_run_preflight_center",
    "default_agent_core_capabilities",
    "agent_core_api_contract",
    "agent_core_replacement_readiness_profile",
    "evaluate_agent_core_api_stability",
    "evaluate_agent_core_runtime_boundary",
    "evaluate_agent_core_readiness",
    "structured_output_feedback",
    "storage_backend_manifest",
    "cosine_similarity",
    "deterministic_text_embedding",
    "rank_semantic_documents",
    "validate_json_schema_subset",
    "TERMINAL_RUN_STATUSES",
    "TERMINAL_PLAN_STEP_STATUSES",
    "TERMINAL_TURN_STATUSES",
    "ToolCenter",
    "ToolCenterCallRecord",
    "ToolCenterTrace",
    "ToolExecutionAttempt",
    "ToolExecutionCenter",
    "ToolExecutionRecord",
    "ToolInvocation",
    "ToolRouteCandidate",
    "ToolRoutePlan",
    "ToolReplayRecord",
    "ToolReplayPort",
    "ToolReplayStorePort",
    "TraceEvalHarness",
    "TraceCorrelationEntry",
    "TraceCorrelationIndex",
    "TraceEvalIssue",
    "TraceEvalReport",
    "TraceEvalSpec",
    "TraceEvaluatorPort",
    "TraceReplayComparator",
    "TraceReplayDiffIssue",
    "TraceReplayDiffReport",
    "TraceReplayDiffSpec",
    "TraceReplayHarness",
    "TraceReplayResult",
    "TraceReplayStep",
    "TransportLLMProvider",
    "ToolRegistry",
    "ToolResult",
    "ToolRuntimeMount",
    "ToolRuntimePort",
    "ToolRetryPolicy",
    "ToolSpec",
    "ToolTrace",
    "TurnState",
    "TurnStatus",
    "UsageInfo",
    "validate_tool_arguments",
    "agent_core_sdk_manifest",
    "run_agent_core_acceptance",
    "run_agent_core_approval_acceptance",
    "run_agent_core_context_acceptance",
    "run_agent_core_orchestration_acceptance",
    "run_agent_core_provider_acceptance",
    "run_agent_core_recovery_acceptance",
    "run_agent_core_resume_acceptance",
    "run_agent_core_storage_acceptance",
    "run_agent_core_validation",
]


def agent_core_sdk_manifest(
    *,
    package_version: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> AgentCoreSDKManifest:
    """Return the package-level SDK manifest with the current public API list."""

    return _build_agent_core_sdk_manifest(
        public_api=tuple(__all__),
        package_version=package_version,
        metadata=metadata,
    )


def agent_core_api_contract(
    *,
    metadata: dict[str, Any] | None = None,
) -> AgentCoreAPIContract:
    """Return the package-root public API stability contract."""

    return _build_agent_core_api_contract(tuple(__all__), metadata=metadata)


def evaluate_agent_core_api_stability(
    *,
    package_version: str | None = None,
    metadata: dict[str, Any] | None = None,
    contract: AgentCoreAPIContract | None = None,
) -> AgentCoreAPIStabilityReport:
    """Evaluate the current package root against the stable API contract."""

    return _evaluate_agent_core_api_stability(
        agent_core_sdk_manifest(package_version=package_version, metadata=metadata),
        contract=contract,
    )


def evaluate_agent_core_readiness(
    profile: AgentCoreReadinessProfile | None = None,
    *,
    package_version: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> AgentCoreReadinessReport:
    """Evaluate the current package root against a readiness profile."""

    return _evaluate_agent_core_readiness(
        agent_core_sdk_manifest(package_version=package_version, metadata=metadata),
        profile=profile,
    )


def evaluate_agent_core_runtime_boundary(
    *,
    metadata: dict[str, Any] | None = None,
) -> AgentCoreRuntimeBoundaryReport:
    """Audit the package root for forbidden runtime dependencies and packages."""

    return _evaluate_agent_core_runtime_boundary(
        agent_core_sdk_manifest(metadata=metadata),
        metadata=metadata,
    )


async def run_agent_core_acceptance(
    *,
    task: str = "inspect target",
    metadata: dict[str, Any] | None = None,
) -> AgentCoreAcceptanceReport:
    """Run the default pure-SDK acceptance scenario against the package root."""

    return await _run_agent_core_acceptance(
        sdk_manifest=agent_core_sdk_manifest(metadata=metadata),
        task=task,
        metadata=metadata,
    )


async def run_agent_core_validation(
    *,
    metadata: dict[str, Any] | None = None,
) -> AgentCoreValidationReport:
    """Run all package-level SDK validation gates against the package root."""

    return await _run_agent_core_validation(
        sdk_manifest=agent_core_sdk_manifest(metadata=metadata),
        metadata=metadata,
    )

